name: CI

on: [push, pull_request]

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y openmpi-bin
    - run: cargo fmt --all -- --check
    - run: cargo build
    - run: cargo run
    - run: cargo test
    - run: cargo clippy
